#! /usr/bin/python

import argparse

from mj import Main, get_version

parser = argparse.ArgumentParser(description='mahjonggstats')
parser.add_argument('--name', '-n', help='select only this level name')
parser.add_argument('--level-names-only', '-l', action='store_true', help='show level names only')
parser.add_argument('--verbose', action='store_true', help='show level names and averages only')
parser.add_argument('--version', '-v', action='version', version=f"version={get_version()}", help='show program version and exit')
kwargs = vars(parser.parse_args())

try:
    main = Main(**kwargs)
    main.run()
except ValueError as ex:
    print(ex)
except RuntimeError as ex:
    print(ex)
